// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameInterfaceInfo = "interface_info"

// InterfaceInfo 接口信息表
type InterfaceInfo struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	Name      string         `gorm:"column:name;not null;comment:接口名称" json:"name"`                                       // 接口名称
	Desc      *string        `gorm:"column:desc;comment:接口描述" json:"desc"`                                                // 接口描述
	URL       string         `gorm:"column:url;not null;comment:接口地址" json:"url"`                                         // 接口地址
	ReqParams string         `gorm:"column:req_params;not null;comment:请求参数" json:"req_params"`                           // 请求参数
	ReqHeader *string        `gorm:"column:req_header;comment:请求头" json:"req_header"`                                     // 请求头
	RepHeader *string        `gorm:"column:rep_header;comment:响应头" json:"rep_header"`                                     // 响应头
	Status    int32          `gorm:"column:status;not null;comment:接口状态（0-closed，1-open）" json:"status"`                  // 接口状态（0-closed，1-open）
	Method    string         `gorm:"column:method;not null;comment:请求类型" json:"method"`                                   // 请求类型
	UserID    int64          `gorm:"column:user_id;not null;comment:创建人" json:"user_id"`                                  // 创建人
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;default:CURRENT_TIMESTAMP;comment:软删除（gorm）" json:"deleted_at"`     // 软删除（gorm）
}

// TableName InterfaceInfo's table name
func (*InterfaceInfo) TableName() string {
	return TableNameInterfaceInfo
}
