// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_user"

// SysUser 用户表
type SysUser struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	UserName    string         `gorm:"column:user_name;not null;comment:用户名称" json:"user_name"`                             // 用户名称
	UserAccount *string        `gorm:"column:user_account;comment:账号(可选，本地登录用)" json:"user_account"`                        // 账号(可选，本地登录用)
	AvatarURL   *string        `gorm:"column:avatar_url;comment:用户头像" json:"avatar_url"`                                    // 用户头像
	Email       string         `gorm:"column:email;not null;comment:用户邮箱" json:"email"`                                     // 用户邮箱
	AccessKey   string         `gorm:"column:access_key;not null;comment:API调用凭证AK" json:"access_key"`                      // API调用凭证AK
	SecretKey   string         `gorm:"column:secret_key;not null;comment:API调用凭证SK" json:"secret_key"`                      // API调用凭证SK
	Status      int32          `gorm:"column:status;not null;comment:用户状态：0-正常，1-封禁" json:"status"`                         // 用户状态：0-正常，1-封禁
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;default:CURRENT_TIMESTAMP;comment:软删除（Gorm-ORM）" json:"deleted_at"` // 软删除（Gorm-ORM）
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
