// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserAuth = "sys_user_auth"

// SysUserAuth 用户授权关联表
type SysUserAuth struct {
	ID           int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                            // ID
	UserID       int64   `gorm:"column:user_id;not null;comment:关联sys_user的ID" json:"user_id"`                            // 关联sys_user的ID
	IdentityType string  `gorm:"column:identity_type;not null;comment:类型: github, google, password" json:"identity_type"` // 类型: github, google, password
	Identifier   string  `gorm:"column:identifier;not null;comment:唯一标识: openid, 账号名等" json:"identifier"`                 // 唯一标识: openid, 账号名等
	Credential   *string `gorm:"column:credential;comment:凭证: 密码hash或token" json:"credential"`                            // 凭证: 密码hash或token
}

// TableName SysUserAuth's table name
func (*SysUserAuth) TableName() string {
	return TableNameSysUserAuth
}
