// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRole = "sys_role"

// SysRole 角色表
type SysRole struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:角色ID" json:"id"`   // 角色ID
	RoleName  string    `gorm:"column:role_name;not null;comment:角色名称(如：管理员)" json:"role_name"`   // 角色名称(如：管理员)
	RoleKey   string    `gorm:"column:role_key;not null;comment:角色权限标识(如：admin)" json:"role_key"` // 角色权限标识(如：admin)
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
