server:
  port: 3000
  mode: debug
  frontendURL: "http://localhost:5173"

mysql:
  host: 127.0.0.1   # 不另外设置时，默认为127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  dbname: yuetu_api
  user: root
  password: 12345678
  logLevel: error

redis:
  ip: 127.0.0.1
  port: 6379
  password: 12345678
  poolSize: 100

jwt:
  expires: 24  # 过期时间（hour）
  issuer: "rabit"  # 签发人
  secretKey: ""

oauth:
  github:
    clientID: "Ov23liJ4OHz0UJFMXvhj"
    clientSecret: "06833c8890612e0f502fa1dc4f77796c0c591249"
    redirectURL: "http://localhost:3000/api/v1/auth/github/callback"