// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	InterfaceInfo *interfaceInfo
	SysRole       *sysRole
	SysUser       *sysUser
	SysUserAuth   *sysUserAuth
	SysUserRole   *sysUserRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	InterfaceInfo = &Q.InterfaceInfo
	SysRole = &Q.SysRole
	SysUser = &Q.SysUser
	SysUserAuth = &Q.SysUserAuth
	SysUserRole = &Q.SysUserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		InterfaceInfo: newInterfaceInfo(db, opts...),
		SysRole:       newSysRole(db, opts...),
		SysUser:       newSysUser(db, opts...),
		SysUserAuth:   newSysUserAuth(db, opts...),
		SysUserRole:   newSysUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	InterfaceInfo interfaceInfo
	SysRole       sysRole
	SysUser       sysUser
	SysUserAuth   sysUserAuth
	SysUserRole   sysUserRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		InterfaceInfo: q.InterfaceInfo.clone(db),
		SysRole:       q.SysRole.clone(db),
		SysUser:       q.SysUser.clone(db),
		SysUserAuth:   q.SysUserAuth.clone(db),
		SysUserRole:   q.SysUserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		InterfaceInfo: q.InterfaceInfo.replaceDB(db),
		SysRole:       q.SysRole.replaceDB(db),
		SysUser:       q.SysUser.replaceDB(db),
		SysUserAuth:   q.SysUserAuth.replaceDB(db),
		SysUserRole:   q.SysUserRole.replaceDB(db),
	}
}

type queryCtx struct {
	InterfaceInfo *interfaceInfoDo
	SysRole       *sysRoleDo
	SysUser       *sysUserDo
	SysUserAuth   *sysUserAuthDo
	SysUserRole   *sysUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		InterfaceInfo: q.InterfaceInfo.WithContext(ctx),
		SysRole:       q.SysRole.WithContext(ctx),
		SysUser:       q.SysUser.WithContext(ctx),
		SysUserAuth:   q.SysUserAuth.WithContext(ctx),
		SysUserRole:   q.SysUserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
