// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend-go/internal/dal/model"
)

func newSysUserAuth(db *gorm.DB, opts ...gen.DOOption) sysUserAuth {
	_sysUserAuth := sysUserAuth{}

	_sysUserAuth.sysUserAuthDo.UseDB(db, opts...)
	_sysUserAuth.sysUserAuthDo.UseModel(&model.SysUserAuth{})

	tableName := _sysUserAuth.sysUserAuthDo.TableName()
	_sysUserAuth.ALL = field.NewAsterisk(tableName)
	_sysUserAuth.ID = field.NewInt64(tableName, "id")
	_sysUserAuth.UserID = field.NewInt64(tableName, "user_id")
	_sysUserAuth.IdentityType = field.NewString(tableName, "identity_type")
	_sysUserAuth.Identifier = field.NewString(tableName, "identifier")
	_sysUserAuth.Credential = field.NewString(tableName, "credential")

	_sysUserAuth.fillFieldMap()

	return _sysUserAuth
}

// sysUserAuth 用户授权关联表
type sysUserAuth struct {
	sysUserAuthDo

	ALL          field.Asterisk
	ID           field.Int64  // ID
	UserID       field.Int64  // 关联sys_user的ID
	IdentityType field.String // 类型: github, google, password
	Identifier   field.String // 唯一标识: openid, 账号名等
	Credential   field.String // 凭证: 密码hash或token

	fieldMap map[string]field.Expr
}

func (s sysUserAuth) Table(newTableName string) *sysUserAuth {
	s.sysUserAuthDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysUserAuth) As(alias string) *sysUserAuth {
	s.sysUserAuthDo.DO = *(s.sysUserAuthDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysUserAuth) updateTableName(table string) *sysUserAuth {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.UserID = field.NewInt64(table, "user_id")
	s.IdentityType = field.NewString(table, "identity_type")
	s.Identifier = field.NewString(table, "identifier")
	s.Credential = field.NewString(table, "credential")

	s.fillFieldMap()

	return s
}

func (s *sysUserAuth) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysUserAuth) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["identity_type"] = s.IdentityType
	s.fieldMap["identifier"] = s.Identifier
	s.fieldMap["credential"] = s.Credential
}

func (s sysUserAuth) clone(db *gorm.DB) sysUserAuth {
	s.sysUserAuthDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysUserAuth) replaceDB(db *gorm.DB) sysUserAuth {
	s.sysUserAuthDo.ReplaceDB(db)
	return s
}

type sysUserAuthDo struct{ gen.DO }

func (s sysUserAuthDo) Debug() *sysUserAuthDo {
	return s.withDO(s.DO.Debug())
}

func (s sysUserAuthDo) WithContext(ctx context.Context) *sysUserAuthDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysUserAuthDo) ReadDB() *sysUserAuthDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysUserAuthDo) WriteDB() *sysUserAuthDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysUserAuthDo) Session(config *gorm.Session) *sysUserAuthDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysUserAuthDo) Clauses(conds ...clause.Expression) *sysUserAuthDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysUserAuthDo) Returning(value interface{}, columns ...string) *sysUserAuthDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysUserAuthDo) Not(conds ...gen.Condition) *sysUserAuthDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysUserAuthDo) Or(conds ...gen.Condition) *sysUserAuthDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysUserAuthDo) Select(conds ...field.Expr) *sysUserAuthDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysUserAuthDo) Where(conds ...gen.Condition) *sysUserAuthDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysUserAuthDo) Order(conds ...field.Expr) *sysUserAuthDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysUserAuthDo) Distinct(cols ...field.Expr) *sysUserAuthDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysUserAuthDo) Omit(cols ...field.Expr) *sysUserAuthDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysUserAuthDo) Join(table schema.Tabler, on ...field.Expr) *sysUserAuthDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysUserAuthDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysUserAuthDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysUserAuthDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysUserAuthDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysUserAuthDo) Group(cols ...field.Expr) *sysUserAuthDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysUserAuthDo) Having(conds ...gen.Condition) *sysUserAuthDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysUserAuthDo) Limit(limit int) *sysUserAuthDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysUserAuthDo) Offset(offset int) *sysUserAuthDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysUserAuthDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysUserAuthDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysUserAuthDo) Unscoped() *sysUserAuthDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysUserAuthDo) Create(values ...*model.SysUserAuth) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysUserAuthDo) CreateInBatches(values []*model.SysUserAuth, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysUserAuthDo) Save(values ...*model.SysUserAuth) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysUserAuthDo) First() (*model.SysUserAuth, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) Take() (*model.SysUserAuth, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) Last() (*model.SysUserAuth, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) Find() ([]*model.SysUserAuth, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysUserAuth), err
}

func (s sysUserAuthDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserAuth, err error) {
	buf := make([]*model.SysUserAuth, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysUserAuthDo) FindInBatches(result *[]*model.SysUserAuth, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysUserAuthDo) Attrs(attrs ...field.AssignExpr) *sysUserAuthDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysUserAuthDo) Assign(attrs ...field.AssignExpr) *sysUserAuthDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysUserAuthDo) Joins(fields ...field.RelationField) *sysUserAuthDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysUserAuthDo) Preload(fields ...field.RelationField) *sysUserAuthDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysUserAuthDo) FirstOrInit() (*model.SysUserAuth, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) FirstOrCreate() (*model.SysUserAuth, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) FindByPage(offset int, limit int) (result []*model.SysUserAuth, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysUserAuthDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysUserAuthDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysUserAuthDo) Delete(models ...*model.SysUserAuth) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysUserAuthDo) withDO(do gen.Dao) *sysUserAuthDo {
	s.DO = *do.(*gen.DO)
	return s
}
